version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: circleci/snyk@0.0.7

jobs:
  build:
    executor: maven/default
    steps:
      - checkout
      - run: mvn clean install

  test:
    executor: maven/default
    steps:
      - checkout
      - run: mvn test

  snyk_scan:
    docker:
      - image: snyk/snyk-cli:latest
    steps:
      - checkout
      - run:
          name: Snyk Scan
          command: snyk test
        # Fail if vulnerabilities are found
        when: on_fail

  docker_build:
    executor: docker/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t your-docker-image-name .

  deploy:
    docker:
      - image: openjdk:17.0.8
    steps:
      - setup_remote_docker
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a getsuki-su-devops
            heroku container:release web -a getsuki-su-devops

workflows:
  version: 2
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
      - snyk_scan:
          requires:
            - test
          filters:
            branches:
              only: develop

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release
      - snyk_scan:
          requires:
            - test
          filters:
            branches:
              only: release
      - docker_build:
          requires:
            - snyk_scan
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - docker_build
          filters:
            branches:
              only: release